[project]
name = "datox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numpy>=2.0.2",
    "pandas>=2.2.3",
    "pandastable>=0.14.0",
    "scipy>=1.13.1",
    "seaborn>=0.13.2",
]
